version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
  ports:
    - "80:80"
  networks:
    - notes-app
  restart: always

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test_db
  volumes:
    - mysql-data:/var/lib/mysql
  networks:
    - notes-app
  restart: always  


django:
  build:
    context: .
  container_name: django_cont
  command: sh -c "python manage.py migrate  --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
  ports: 
   - "8000:8000"
  env_file:
    - " .env"
  restart: always 

  volumes:
    mysql-data:     

networks:    
  notes-app:
